### ISSUE TITLE
Error 69 when installing: poopfac

### ISSUE THREAD

**Issue by realDiVIbil** [xs4u/Windows11UpdateRequirementsBypasser#2]
Hello, today I was installing Windows 11 Update Requirements Bypasser, and when installing I got "Error: 69" which says "Poopfac". How can I fix that?

**Comment by xs4u** [comment]
it means epic is a lie

it also means that microsoft has poop-faced your appraiserres.dll

**Comment by realDiVIbil** [comment]
how do i patch this?

**Comment by xs4u** [comment]
you have to suddenly use setup from any build lower than 25951 to do it


R.I.P
In-Place Upgrade without Bypass11
2021-2023

**Comment by xs4u** [comment]
or as I said, use bypass11 from MediaCreationTool.bat on Github
